# Generated by Django 4.1.7 on 2023-05-09 12:29

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Configuration", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator("^[a-zA-Z0-9À-ÿ ]+$")
                        ],
                        verbose_name="Nom de l'événement",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=1000, verbose_name="Description de l'événement"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="Images/",
                        verbose_name="Image(s) de l'événement(s)",
                    ),
                ),
                (
                    "duration",
                    models.TimeField(
                        default="02:00", verbose_name="Durée de l'événement"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("DRF", "Draft"),
                            ("ACT", "Active"),
                            ("ARC", "Archived"),
                        ],
                        default="DRF",
                        max_length=3,
                        verbose_name="Etat de l'event brouillon/actif/archivé",
                    ),
                ),
                ("artiste", models.CharField(max_length=70, verbose_name="Artistes")),
                (
                    "configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Configuration.config",
                    ),
                ),
                ("user", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="Representation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 5, 9, 14, 29, 28, 118711),
                        verbose_name="Date",
                    ),
                ),
                (
                    "remaining_seats",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Informations de la salle"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("DRF", "Draft"),
                            ("ACT", "Active"),
                            ("ARC", "Archived"),
                        ],
                        default="DRF",
                        max_length=3,
                        verbose_name="Representation active ou archivée",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Event.event"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(max_length=50, verbose_name="Nom de l'élément"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=3,
                        verbose_name="Prix de l'élément'",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Event.event"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CodePromo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Le code à introduire"
                    ),
                ),
                (
                    "amount",
                    models.FloatField(
                        blank=True, default=0, verbose_name="Montant fixe de réduction"
                    ),
                ),
                (
                    "percentage",
                    models.FloatField(
                        blank=True,
                        default=0,
                        verbose_name="Pourcentage de reduction sur le prix total",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Event.event"
                    ),
                ),
            ],
        ),
    ]
