# Generated by Django 4.1.7 on 2023-04-17 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 17, 10, 58, 55, 518354), verbose_name='Date'),
        ),
    ]
