# Generated by Django 4.1.7 on 2023-03-17 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 17, 17, 4, 2, 654352), verbose_name='Date'),
        ),
    ]
