# Generated by Django 4.1.6 on 2023-02-20 11:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenement',
            name='configuration',
        ),
        migrations.AlterField(
            model_name='evenement',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='college.admin'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='even_illustration',
            field=models.ImageField(blank=True, null=True, upload_to='url mis dans MEDIA_ROOT dans settings', verbose_name="Image(s) de l'évènement(s)"),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reserv_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 20, 12, 28, 10, 396358), verbose_name='Date de la réservation'),
        ),
    ]
