# Generated by Django 4.1.7 on 2023-02-20 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_alter_reservation_reserv_date_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='admin_date_creation',
            field=models.DateField(default=datetime.datetime(2023, 2, 20, 16, 5, 24, 928479), verbose_name='Date de création du compte'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reserv_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 20, 16, 5, 24, 929479), verbose_name='Date de la réservation'),
        ),
    ]
