# Generated by Django 4.1.7 on 2023-02-21 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0007_alter_admin_admin_date_creation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='reserv_boisson',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='reserv_nourriture',
        ),
        migrations.AddField(
            model_name='ticket',
            name='reserv_boisson',
            field=models.IntegerField(default=0, verbose_name='Ticket boisson pris avec la réservation'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='reserv_nourriture',
            field=models.IntegerField(default=0, verbose_name='Ticket nourriture pris avec la réservation'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='admin_date_creation',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 21, 11, 45, 7, 99714), verbose_name='Date de création du compte'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reserv_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 21, 11, 45, 7, 101696), verbose_name='Date de la réservation'),
        ),
    ]
