# Generated by Django 4.1.7 on 2023-02-21 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0009_alter_admin_admin_date_creation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='admin_is_archived',
            field=models.BooleanField(default=False, verbose_name='Admin archivé'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='admin_date_creation',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 21, 15, 39, 29, 537092), verbose_name='Date de création du compte'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='admin_password',
            field=models.CharField(max_length=100, verbose_name="Mot de passe de l'admin"),
        ),
        migrations.AlterField(
            model_name='admin',
            name='admin_pseudo',
            field=models.CharField(max_length=50, verbose_name="Pseudo de l'admin"),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reserv_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 21, 15, 39, 29, 538092), verbose_name='Date de la réservation'),
        ),
    ]
