# Generated by Django 4.1.6 on 2023-02-20 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_remove_evenement_configuration_alter_evenement_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='even_illustration',
            field=models.ImageField(blank=True, null=True, upload_to='Images', verbose_name="Image(s) de l'évènement(s)"),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reserv_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 20, 12, 44, 40, 594164), verbose_name='Date de la réservation'),
        ),
    ]
