# Generated by Django 4.1.7 on 2023-02-20 12:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0003_alter_evenement_even_illustration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reserv_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 20, 13, 3, 17, 567562), verbose_name='Date de la réservation'),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_siege', models.CharField(max_length=3, verbose_name='Trigramme du siège')),
                ('Reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.reservation')),
            ],
        ),
    ]
