# Generated by Django 4.1.7 on 2023-02-28 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_alter_evenement_even_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='even_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 28, 10, 1, 51, 931974), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reserv_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 28, 10, 1, 51, 931974), verbose_name='Date de la réservation'),
        ),
    ]
