# Generated by Django 4.1.7 on 2023-02-28 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0007_user_is_staff_alter_evenement_even_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='even_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 28, 10, 48, 56, 356705), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reserv_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 28, 10, 48, 56, 357705), verbose_name='Date de la réservation'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Dernier login'),
        ),
    ]
