# Generated by Django 4.1.7 on 2023-02-21 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0008_remove_reservation_reserv_boisson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='admin_date_creation',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 21, 15, 28, 56, 772907), verbose_name='Date de création du compte'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reserv_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 21, 15, 28, 56, 773907), verbose_name='Date de la réservation'),
        ),
    ]
