# Generated by Django 4.1.7 on 2023-02-23 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0014_alter_admin_admin_date_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='admin_date_creation',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 23, 16, 29, 47, 31008), verbose_name='Date de création du compte'),
        ),
        migrations.AlterField(
            model_name='codepromo',
            name='codepromo_montant',
            field=models.FloatField(blank=True, default=0, verbose_name='Montant fixe de réduction'),
        ),
        migrations.AlterField(
            model_name='codepromo',
            name='codepromo_pourcentage',
            field=models.FloatField(blank=True, default=0, verbose_name='Pourcentage de reduction sur le prix total'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reserv_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 23, 16, 29, 47, 32008), verbose_name='Date de la réservation'),
        ),
    ]
