# Generated by Django 4.1.7 on 2023-02-24 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0015_alter_admin_admin_date_creation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='configuration_salle',
            field=models.CharField(choices=[('1', 'classique'), ('2', 'espacée'), ('3', 'proche')], default='classique', max_length=2000, verbose_name='Configuration de la salle'),
        ),
        migrations.AddField(
            model_name='evenement',
            name='event_time',
            field=models.TimeField(default=datetime.datetime.now, verbose_name='Heure'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='admin_date_creation',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 24, 7, 36, 21, 881179), verbose_name='Date de création du compte'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='even_date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reserv_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 24, 7, 36, 21, 882593), verbose_name='Date de la réservation'),
        ),
    ]
