# Generated by Django 4.1.7 on 2023-02-24 07:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0016_evenement_configuration_salle_evenement_event_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='admin_date_creation',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 24, 7, 41, 37, 720142), verbose_name='Date de création du compte'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='even_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reserv_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 24, 7, 41, 37, 721980), verbose_name='Date de la réservation'),
        ),
    ]
