# Generated by Django 4.1.7 on 2023-02-24 07:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0018_alter_admin_admin_date_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='admin_date_creation',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 24, 7, 56, 44, 552932), verbose_name='Date de création du compte'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='even_date',
            field=models.DateField(default=datetime.date(1999, 1, 1), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reserv_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 24, 7, 56, 44, 554080), verbose_name='Date de la réservation'),
        ),
    ]
