# Generated by Django 4.1.7 on 2023-02-24 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0021_alter_admin_admin_date_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='admin_date_creation',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 24, 9, 51, 29, 558505), verbose_name='Date de création du compte'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='even_illustration',
            field=models.ImageField(blank=True, null=True, upload_to='../Media/Images', verbose_name="Image(s) de l'évènement(s)"),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reserv_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 24, 9, 51, 29, 559772), verbose_name='Date de la réservation'),
        ),
    ]
