# Generated by Django 4.1.7 on 2023-02-24 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0023_alter_admin_admin_date_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='admin_date_creation',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 24, 10, 16, 30, 271973), verbose_name='Date de création du compte'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='even_illustration',
            field=models.ImageField(blank=True, null=True, upload_to='Images/', verbose_name="Image(s) de l'évènement(s)"),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reserv_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 24, 10, 16, 30, 273233), verbose_name='Date de la réservation'),
        ),
    ]
