# Generated by Django 4.1.7 on 2023-03-17 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='name',
            new_name='last_name',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 17, 17, 56, 47, 690795), verbose_name='Date de la réservation'),
        ),
    ]
